spring.application.name=PortfolioForecasting

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/pf
spring.datasource.username=root
spring.datasource.password=root


# Hibernate
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# MySQL Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#Finnhub Api key 
finnhub.api.key=da38dk9r01qupvfc2n6gda38dk9r01qupvfc2n70


#Fmp Api key 
fmp.api.key=WPQoTGfXp5A464ThwXpOcE0lkf7c5Ugt